[package]
name = "rust-consumer"
version = "0.1.0"
edition = "2018"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[dependencies]
rdkafka = { version = "0.26", features = ["cmake-build"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
